package cosmetic.modelo.entidad;

public enum CategoriaCosmetica {

	JABON, JABONDEGLICERINA, JABONGEL, CHAMPU, CHAMPUSOLIDO, CREMA, CREMASOLIDA, GELBAÑO, BOMBABAÑO, SALBAÑO, UNGUENTO,
	MANTECABATIDA, GELATINABAÑO, JABONGELATINA
}
